using UnityEngine;

public enum Suit
{ HEARTS, DIAMONDS, CLUBS, SPADES, JOKER, HIDDEN }

public enum Rank
{ ACE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING, JOKER, HIDDEN }